language: python
matrix:
    include:
        - name: "Python 3.7 on Xenial Linux"
          python: 3.7 
        - name: "Python 3.8 on Xenial Linux"
          python: 3.8 
        - name: "Python 3.9 on Xenial Linux"
          python: 3.9 
addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 it is part of libnetcdf-dev)
      - gfortran

install: 
    - python --version
    - python3 --version
    - pip3 install -U pip
    - pip3 install -r requirements.txt
    - pip3 install -r dev-requirements.txt    
    - pip3 install .

default:
  - step:
      script:
        - chmod +x *
        - coverage run -m pytest tests/run_all_tests.py

branches:
    only:
    - main
after_success:
    - bash <(curl -s https://codecov.io/bash)
