language: python
matrix:
    include:
        - name: "Python 3.7 on Xenial Linux"
          python: 3.7 
        - name: "Python 3.8 on Xenial Linux"
          python: 3.8 
        - name: "Python 3.9 on Xenial Linux"
          python: 3.9 
before_install:
    - chmod a+x ./Test_01
addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin
      - gfortran
install: 
    - python --version
    - python3 --version
    - pip3 install -U pip
    - pip3 install -r requirements.txt
    - pip3 install -r dev-requirements.txt    
    - pip3 install .
    - pip install codecov
    - pip install pytest-cov
script:
    - coverage run -m pytest ./tests/run_all_tests.py
branches:
    only:
    - main
after_success:
    - bash <(curl --connect-timeout 10 --retry 10 --retry-max-time 0 https://codecov.io/bash) || (sleep 30 && bash <(curl --connect-timeout 10 --retry 10 --retry-max-time 0 https://codecov.io/bash))
