{
    "codecov": {
        "token": "as9v6enmrM30abQBAtJMgOT8RM5lPOt+2xbCcFpd0asMtqn0jybJiqizoX+3yj9t5ANTpi4P/txUFGlqnqJSt+iOlLh4M1BA07n8aJVFljA=",
        "notify": {
            "wait_for_ci": true
        },
        "require_ci_to_pass": true
    },
    "coverage": {
        "range": [
            80,
            90
        ],
        "round": "down",
        "status": {
            "patch": {
                "default": {
                    "enabled": false
                }
            },
            "project": {
                "default": {
                    "target": 1,
                    "enabled": true,
                    "threshold": 0.1
                }
            }
        },
        "precision": 2
    }
}