codecov:
  token: as9v6enmrM30abQBAtJMgOT8RM5lPOt+2xbCcFpd0asMtqn0jybJiqizoX+3yj9t5ANTpi4P/txUFGlqnqJSt+iOlLh4M1BA07n8aJVFljA=
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 80...90

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project:
      default:
        enabled: yes
        target: 1
        threshold: 0.1
    patch:
      default:
        enabled: off