{
    "codecov": {
        "token": 
        "notify": {
            "wait_for_ci": true
        },
        "require_ci_to_pass": true
    },
    "coverage": {
        "range": [
            70,
            100
        ],
        "round": "down",
        "status": {
            "patch": {
                "default": {
                    "enabled": false
                }
            },
            "project": {
                "default": {
                    "target": 1,
                    "enabled": true,
                    "threshold": 0.1
                }
            }
        },
        "precision": 2
    }
}